server:
  port: ${PORT:${SERVER_PORT:0}}
  
spring:
  application:
    name: catalog-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27018

exchange:
  persona:
    name: PeliculaExchange
queue:
  pelicula:
    name: PeliculaQueue

message: PeliculaQueue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enable: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: "catalog-service"
    description: "Microservicio de catálogo -> parcial Especializacion Backend I"
