server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enable: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: "gateway"
    description: "Gateway -> parcial Especializacion Backend I"