server:
  port: 0

spring:
  application:
    name: serie-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017
  zipkin:
    base-url: http://localhost:9411/
    enabled: true


queue:
  serie:
    name: SerieQueue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enable: true
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
info:
  app:
    name: "serie-service"
    description: "Microservicio de serie -> parcial Especializacion Backend I"